import Grid from "@/components/icons/Grid";
import Add from "@/components/icons/Add";
import { SidebarItem } from "@/types";

export const sidebarItems: SidebarItem[] = [
  {
    label: "Dashboard",
    href: "/dashboard",
    Icon: Grid,
  },
  {
    label: "Product Form",
    href: "/product-form",
    Icon: Add,
  },
  {
    label: "Categories",
    href: "/categories",
    Icon: Add,
  },
];

export const countries = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Japan",
  "Italy",
  "Spain",
  "Brazil",
  "India",
  "China",
  "Russia",
  "Mexico",
  "South Korea",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Switzerland",
  "Austria",
  "Belgium",
  "Portugal",
  "Greece",
  "Ireland",
  "New Zealand",
  "Singapore",
  "Malaysia",
  "Thailand",
  "Vietnam",
  "Indonesia",
  "Philippines",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",
  "Morocco",
  "Turkey",
  "Israel",
  "Saudi Arabia",
  "United Arab Emirates",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Poland",
  "Ukraine",
  "Romania",
  "Hungary",
];
